### ISSUE TITLE
episode 05 - The Research Data Life Cycle draft is ready for initial review

### ISSUE THREAD

**Issue by aromanowski** [carpentries-incubator/fair-bio-practice#21]
Hi everyone,
I have just pushed episode 05 on a branch I created:
https://github.com/carpentries-incubator/fair-bio-practice/blob/update-episode-04-and-05/_episodes/05-the-research-data-life-cycle.md

Could you please have a look and tell me what you think about it? Any ideas or suggestions to improve it?

Total episode time: 30 minutes max.

All the best,
Andrés

**Comment by Boehmin** [comment]
Hi Andrew,
The general outline is good. I would keep in mind the 'story' and what the learners should take away/learn from this lesson (objectives). I would start with Objective 1) What is the natural research data life cycle? (since this is the introduction) - We assume most attendees have already published, but we need to frame the context and set the scope for the rest of the course. Also, we can't assume that everyone has been fully involved in the publication process.
That naturally leads to Objective 2) Why does planning make it easier to be FAIR?
Followed by Objective 3) What actions can help in FAIR?
Therefore I would follow with Objective 4) **Briefly** touch upon what is a data management plan/or what is the purpose of a data management plan (consider metadata generation, data storage/preservation, re-use and sharing - that's the questions that they will be answering in their homework). - Get them to make DMP for their homework as you did. [University of Leicester](https://www2.le.ac.uk/services/research-data/old-2019-12-11/create-data/DMPlan#:~:text=The%20goal%20of%20a%20data,for%20preservation%20in%20the%20future.%E2%80%9D&text=Data%20preservation%2C%20re%2Duse%20and%20sharing) has a couple of good questions as well, we could recycle some of these? 

This shouldn't take longer than 30 min I believe as the last bit is homework. This doesn't change what is there, but should help tell the story a little better and drive home the message/objectives. Hope this makes sense :)

**Comment by tzielins** [comment]
I have some changes but I think it is better/easier if I made them then delegating. 

Could you please put the slide file that you used to making graphics into files.

**Comment by tzielins** [comment]
more managment/fair actions added to the cycle excerice. Effort is now in the wellcome. Episode. reflowed
