### ISSUE TITLE
Add text on patents and licences

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/fair-bio-practice#23]
After the barriers description. Need to clarify date for patent and copyright. The info that data cannot be copyrighted etc.

**Comment by tzielins** [comment]
Some materials, 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiA5rOduq7wAhVLUcAKHcbkBd4QFjANegQIBxAD&url=https%3A%2F%2Fosf.io%2Fpreprints%2Fsocarxiv%2F8agp9%2Fdownload&usg=AOvVaw3EHSP_1vGvX68fie1J6b80
(pdf doc)

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiA5rOduq7wAhVLUcAKHcbkBd4QFjABegQIAxAD&url=https%3A%2F%2Fpublications.jrc.ec.europa.eu%2Frepository%2Fbitstream%2FJRC106998%2Fkj1a28661enn.pdf&usg=AOvVaw2EWpzvBhRj9F35e6hZAhe0


https://junanaguy.medium.com/its-time-to-eliminate-patents-in-universities-51e6d95362f0
https://www.wilsoncenter.org/blog-post/open-science-and-intellectual-property-using-open-licenses-open-your-science

**Comment by Boehmin** [comment]
This is all a bit of a black hole as for example you can patent processes that 'create' data. You can't patent lists (which are data) but if your novel invention generates certain data (e.g. in silico screening of drug targets), then that process, if it is novel, could certainly get a patent. You could then sue anyone who also uses your data and claim they used your method unless they can prove otherwise ;) But we are not in America and we don't sue everyone.

This is also a cool article about how lawyers use all the loopholes they can get to patent software, or digital tools. Also UK law and US law is different, US law is very much in favour of corporations who have big money!
https://www.mondaq.com/uk/patent/606858/can-you-patent-software

**Comment by tzielins** [comment]
Done
