### ISSUE TITLE
Impossible number (fair chapter)

### ISSUE THREAD

**Issue by tzielins** [carpentries-incubator/fair-bio-practice#4]
Example of a figure for which numerical data are not attached and could be useful.

AM was suggesting ideas for possible modeling papers at one of the meeting.

Or I believe benedict papers has leaf heatmaps but not individual timeseries.
Anything that shows importance of underlining numerical data

**Comment by Boehmin** [comment]
Great example that is online! I understand what you mean with impossible numbers now, this is then potentially almost all western blot data as well as it is rare that someone attaches raw western blot data (or used to). Or all raw data for that matter. This might be worth highlighting briefly at this point with exactly the modelling point in mind? As this raw data is essential in order to allow other people to model diseases, physiological models etc...

**Comment by aromanowski** [comment]
Hi both,
Yes, indeed I wanted to add the figure directly to our episode but was wondering about copyright from the journal. I was going to ask for permission to reproduce the image. As an alternative, I can re-create it myself in a spreadsheet and share it as an example.

Cheers,
A
